<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-21 at 13:47:24.
 */
App::uses('Bat', 'Model');
class BatTest extends PHPUnit_Framework_TestCase
{
    protected $bat;

    protected function setUp()
    {
        $this->bat = new Bat;
    }

    protected function tearDown()
    {
    }

    public function testHits()
    {
        $this->bat->hits();
        $this->bat->hits();
        $this->assertEquals(array(true,true,false), $this->bat->getAllRunner());
        $this->bat->hits();
        $this->bat->hits();
        $this->assertEquals(1, $this->bat->getScore());
    }

    public function testDoubles()
    {
        $this->bat->doubles();
        $this->assertEquals(array(false,true,false), $this->bat->getAllRunner());
        $this->bat->doubles();
        $this->bat->doubles();
        $this->assertEquals(2, $this->bat->getScore());
    }

    public function testTriples()
    {
        $this->bat->triples();
        $this->assertEquals(array(false,false,true), $this->bat->getAllRunner());
        $this->bat->triples();
        $this->assertEquals(1, $this->bat->getScore());
    }

    /**
     * @covers Bat::getAllRunner
     * @todo   Implement testGetAllRunner().
     */
    public function testGetAllRunner() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Bat::getScore
     * @todo   Implement testGetScore().
     */
    public function testGetScore() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Bat::printRunner
     * @todo   Implement testPrintRunner().
     */
    public function testPrintRunner()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Bat::printScore
     * @todo   Implement testPrintScore().
     */
    public function testPrintScore()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
