<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-14 at 03:40:31.
 */
App::uses('Score', 'Model');
class ScoreTest extends PHPUnit_Framework_TestCase
{
    protected $score;

    protected function setUp()
    {
        $this->score = new Score;
    }

    protected function tearDown()
    {
    }

    /**
     * @covers Score::setScore
     * @todo   Implement testSetScore().
     */
    public function testSetScore()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    public function testGetScore()
    {
        $this->score->setScore(2);

        $this->assertEquals(2, $this->score->getScore());
    }

    public function testIncrementScore()
    {
        $this->score->setScore(2);
        $this->score->incrementScore();

        $this->assertEquals(3, $this->score->getScore());
    }

    public function testResetScore()
    {
        $this->score->setScore(2);
        $this->score->resetScore();

        $this->assertEquals(0, $this->score->getScore());
    }
}
